src/main/java/com/dkey/social/model/Message.java
package com.dkey.social.model;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.validation.constraints.NotBlank;

import org.hibernate.validator.constraints.Length;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode
@ToString
public class Message {
	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	private Long id;
 	@NotBlank(message="Please fill the message")
 	@Length(max=2048, message="Message too long")
	private String text;
 	@Length(max=255, message="Tag value too long")
	private String tag;
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name="user_id")
	private User author;
	
	private String filename;
	

	public Message(String text, String tag) {
		this.text = text;
		this.tag = tag;
	}
	public Message(String text, String tag, User user) {
		this.text = text;
		this.tag = tag;
		this.author = user;
	}
	public String getAuthorName() {
		return author!=null ? author.getUsername() : "<none>";
	}
}

src/main/resources/templates/parts/common.ftl
<#macro page>
<!DOCTYPE HTML>
<html>
<head>
    <title>Social net</title>
    <meta charset="UTF-8" />
    <link rel="stylesheet" href="/static/style.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://www.google.com/recaptcha/api.js" async defer></script>
</head>
<body>
<#include "navbar.ftl">
	<div class="container mt-5" >
		<#nested>
	</div>
	
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>
</#macro>

src/main/resources/templates/parts/login.ftl
<#include "security.ftl" >  
<#macro login path isRegisterForm>
<form action="${path}" method="post">
    <div class="form-group row">
        <label class="col-sm-2 col-form-label">User Name :</label>
        <div class="col-sm-6">
            <input type="text" name="username" value="<#if user??>${user.username}</#if>"
            class="form-control ${(usernameError??)?string('is-invalid','')}" placeholder="User name" />
            <#if usernameError??>
        	<div class="invalid-feedback">
        		${usernameError}
        	</div>
        </#if>
        </div>
    </div>
    <div class="form-group row">
        <label class="col-sm-2 col-form-label">Password:</label>
        <div class="col-sm-6">
            <input type="password" name="password" class="form-control ${(passwordError??)?string('is-invalid','')}" placeholder="Password" />
        	<#if passwordError??>
        	<div class="invalid-feedback">
        		${passwordError}
        	</div>
        </#if>
        </div>
    </div>
    <#if isRegisterForm>
    <div class="form-group row">
        <label class="col-sm-2 col-form-label">Password2:</label>
        <div class="col-sm-6">
            <input type="password" name="password2" class="form-control ${(password2Error??)?string('is-invalid','')}" placeholder="Retype password" />
        	<#if password2Error??>
        	<div class="invalid-feedback">
        		${password2Error}
        	</div>
        </#if>
        </div>
    </div>
        <div class="form-group row">
        <label class="col-sm-2 col-form-label">Email:</label>
        <div class="col-sm-6">
            <input type="email" name="email" value="<#if user??>${user.email}</#if>"
            class="form-control ${(emailError??)?string('is-invalid','')}"
            placeholder="E-mail" />
        	<#if emailError??>
        	<div class="invalid-feedback">
        		${emailError}
        	</div>
        </#if>
        </div>
    </div>
    <div class="col-sm-6">
    	<div class="g-recaptcha" data-sitekey="6LcEsqoZAAAAAD2Bg0rsKBNsLaOVr-VwI2V1QmCl"></div>
    	<#if captchaError??>
        	<div class="alert alert-danger" role="alert">
        		${captchaError}
        	</div>
        </#if>
    </div>
    </#if>
    <input type="hidden" name="_csrf" value="${_csrf.token}" />
    <#if !isRegisterForm><a href="/registration">Add new user</a></#if>
    <button class="btn btn-primary" type="submit">
    <#if isRegisterForm>Create<#else>Sign In</#if></button>
</form>
</#macro>

<#macro logout>
<form action="/logout" method="post">
    <input type="hidden" name="_csrf" value="${_csrf.token}" />
    <button class="btn btn-primary" type="submit"><#if user??>Sign Out<#else>Log in</#if></button>
</form>
</#macro>

src/main/resources/templates/parts/messageEdit.ftl
<a class="btn btn-primary" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
    Message editor
  </a>
<div class="collapse <#if message??>show</#if>" id="collapseExample">
	<div class="form-group mt-3">
    <form method="post" enctype="multipart/form-data">
    	<div class="form-group">
        <input type="text" name="text" class="form-control ${(textError??)?string('is-invalid','')}" 
        	   value="<#if message??>${message.text}</#if>" placeholder="Введите сообщение" />
        <#if textError??>
        	<div class="invalid-feedback">
        		${textError}
        	</div>
        </#if>
        </div>
        <div class="form-group">
        <input type="text" name="tag"  
	        class="form-control ${(tagError??)?string('is-invalid','')}" value="<#if message??> ${message.tag}</#if>" placeholder="Тэг">
            <#if tagError??>
        	<div class="invalid-feedback">
        		${tagError}
        	</div>
        </#if>
        </div>
    
        <div class="form-group">
        <div class="custom-file">
        	<input type="file" name="file" id="customFile">
        	<label class="custom-file-label" for="customFile">
        		Choose file
        	</label>
        </div>
        </div>
        <input type="hidden" name="_csrf" value="${_csrf.token}" />
        <input type="hidden" name="id" value="<#if message??> ${message.id}</#if>" />
        <div class="form-group">
        <button type="submit" class="btn btn-primary">Save message</button>
        </div>
    </form>
    </div>
</div>

src/main/resources/templates/parts/messageList.ftl
<#include "security.ftl">

<div class="card-columns">
<#list messages as message>
<div class="card my-3">
<div>
  	<#if message.filename??>
    		<img src="/img/${message.filename}" class="card-img-top">
    	</#if>
    </div>
    <div class="m-2">
    <span>${message.text!""}</span><br/>
    <i>#${message.tag!""}</i>
    </div>
    <div class="card-footer text-muted">
    	<a href="/user-messages/${message.author.id}">${message.authorName!""}</a>
    	<#if message.author.id == currentUserId>
    	<a class="btn btn-primary" href="/user-messages/${message.author.id}?message=${message.id}">Edit</a>
    	</#if>
    </div>
</div>
<#else>
No message
</#list>
</div>

src/main/resources/templates/parts/navbar.ftl
<#include "security.ftl">
<#import "login.ftl" as l>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Social net</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <#if user??>
      <li class="nav-item">
        <a class="nav-link" href="/main">Messages<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/user-messages/${currentUserId}">My messages<span class="sr-only">(current)</span></a>
      </li>
      </#if>
      <#if isAdmin>
      <li class="nav-item">
        <a class="nav-link" href="/user">User list<span class="sr-only">(current)</span></a>
      </li>
      </#if>
      <#if user??>
      <li class="nav-item">
        <a class="nav-link" href="/user/profile">User profile<span class="sr-only">(current)</span></a>
      </li>
      </#if>
     </ul>
     <div class="navbar-text mr-3"><#if user??>${name}<#else>Please, login</#if></div>
     <@l.logout />
  </div>
  
 </nav>

src/main/resources/templates/parts/security.ftl
<#assign
	known = Session.SPRING_SECURITY_CONTEXT??
>

<#if known>
	<#assign
		user = Session.SPRING_SECURITY_CONTEXT.authentication.principal
		name = user.getUsername()
		isAdmin = user.isAdmin()
		currentUserId = user.getId()
	>
<#else>
	<#assign
		name = "unknown"
		isAdmin = false
		currentUserId = -1
	>
</#if>